<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Judgy'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- BOOTSTRAP STYLES-->
        <link href="<?php echo $this->basePath(); ?>/css/bootstrap.css" rel="stylesheet" />
        <!-- FONTAWESOME STYLES-->
        <link href="<?php echo $this->basePath(); ?>/css/font-awesome.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
        <link href="<?php echo $this->basePath(); ?>/css/custom.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath(); ?>/css/register.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/ng-tags-input.min.css">
        <!-- GOOGLE FONTS-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

    </head>
    <body ng-app="myApp">
    <div id="wrapper">
    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" href="#">Judgy</div>
        </div>
        <?php echo $this->topNavigation; ?>
    </nav>
    <!-- /. NAV TOP  -->

    <?php echo $this->sideNavigation; ?>

    <div id="page-wrapper" >
    <div id="page-inner">
        <?php echo $this->content; ?>
    </div>
    <!-- /. PAGE INNER  -->
    </div>
    <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

    <script src="<?php echo $this->basePath(); ?>/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="<?php echo $this->basePath(); ?>/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="<?php echo $this->basePath(); ?>/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="<?php echo $this->basePath(); ?>/js/custom.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/lib/ui-bootstrap-tpls-0.12.0.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/lib/ng-tags-input.min.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/lib/angular-file-upload.js"></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular-sanitize.min.js'></script>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular.min.js'></script>

    <script src="<?php echo $this->basePath(); ?>/js/angular/controllers.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/angular/app.js"></script>
    </body>
</html>
