<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Judgy'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- bower:css -->
        <link rel="stylesheet" href="../../../../vendor/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="../../../../vendor/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="../../../../vendor/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="../../../../vendor/ng-tags-input/ng-tags-input.min.css" />
        <!-- endbower -->

        <!-- CUSTOM STYLES-->
        <link href="<?php echo $this->basePath(); ?>/css/custom.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath(); ?>/css/register.css" rel="stylesheet" />
        <!-- GOOGLE FONTS-->

    </head>
    <body ng-app="myApp" ng-cloak>
    <div id="wrapper">
    <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" href="#">Judgy</div>
        </div>
        <?php echo $this->topNavigation; ?>
    </nav>
    <!-- /. NAV TOP  -->

    <?php echo $this->sideNavigation; ?>

    <div id="page-wrapper" >
    <div id="page-inner">
        <?php echo $this->content; ?>
    </div>
    <!-- /. PAGE INNER  -->
    </div>
    <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->

    <!-- bower:js -->
    <script src="../../../../vendor/jquery/dist/jquery.js"></script>
    <script src="../../../../vendor/underscore/underscore.js"></script>
    <script src="../../../../vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script src="../../../../vendor/metisMenu/dist/metisMenu.js"></script>
    <script src="../../../../vendor/angular/angular.js"></script>
    <script src="../../../../vendor/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="../../../../vendor/ng-tags-input/ng-tags-input.min.js"></script>
    <script src="../../../../vendor/textAngular/dist/textAngular.min.js"></script>
    <!-- endbower -->
<!--    todo - find out how to do this with grunt-->
    <script src="../../../../vendor/textAngular/dist/textAngular-sanitize.min.js"></script>

    <!-- My angular scripts -->
    <script src="<?php echo $this->basePath(); ?>/js/app.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/controllers.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/directives.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/filters.js"></script>

    <!-- CUSTOM SCRIPTS -->
    <script src="<?php echo $this->basePath(); ?>/js/binary_admin.js"></script>

    </body>
</html>
