<!--sidebar start-->
<aside>
    <div id="sidebar"  class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">

            <li class="sub-menu">
                <a class=""  href="<?php echo $this->url('home'); ?>"><i class="fa fa-home fa-3x"></i>Home</a>
            </li>

            <li class="sub-menu <?php echo ($type == 'algorithm') ? 'active' : ''; ?>">
                <a  class="" href="javascript:;"><i class="fa fa-superscript fa-3x"></i> Algorithms</a>
                <ul class="sub">
                    <li class="<?php echo ($routeName =='algorithms/default' && $action == 'problems') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => 'algorithm')); ?>"><i class="fa fa-list"></i> Problems</a>
                    </li>
                    <li class="<?php echo ($routeName == 'algorithms/default' && $action == 'scoreboard') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'scoreboard', 'type' => 'algorithm')); ?>"><i class="fa fa-bar-chart-o"></i> Scoreboard</a>
                    </li>
                    <li class="<?php echo ($routeName == 'algorithms/default' && $action == 'competitions') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'competitions', 'type' => 'algorithm')); ?>"><i class="fa fa-clock-o"></i> Competitions</a>
                    </li>
                    <li class="<?php echo ($routeName == 'algorithms/default' && $action == 'tutorials') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'tutorials', 'type' => 'algorithm')); ?>"><i class="fa fa-file-o"></i> Tutorials</a>
                    </li>
                    <li class="<?php echo ($routeName == 'algorithms/default' && $action == 'submit') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'submit', 'type' => 'algorithm')); ?>"><i class="fa fa-envelope-o"></i> Submit</a>
                    </li>
                </ul>
            </li>
            <li class="sub-menu <?php echo ($type === 'arena') ? 'active' : ''; ?>">
                <a  class="" href="javascript:;"><i class="fa fa-crosshairs fa-3x"></i> Arena</a>
                <ul class="sub">
                    <li class="<?php echo ($routeName =='arena-view/default' && $action == 'active') ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url('arena-view/default', array('action' => 'active')); ?>"><i class="fa fa-list"></i> Open arenas</a>
                    </li>
                </ul>
            </li>
            <li class="sub-menu <?php echo ($type === 'misc') ? 'active' : ''; ?>">
                <a  href="#"><i class="fa fa-meh-o fa-3x"></i> Other problems</a>
                <ul class="sub">
                    <li>
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => 'misc')); ?>"><i class="fa fa-list"></i> Questions</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'scoreboard', 'type' => 'misc')); ?>"><i class="fa fa-bar-chart-o"></i> Scoreboard</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('problems-view/default', array('action' => 'submit', 'type' => 'misc')); ?>"><i class="fa fa-envelope-o"></i> Submit</a>
                    </li>
                </ul>
            </li>

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>

