<!--header start-->
<header class="header black-bg">
    <!--logo start-->
    <a href="index.html" class="logo"><b>Judgy</b></a>
    <!--logo end-->
    <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
        <ul class="nav top-menu">
            <!-- settings start -->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                    <?php echo $this->user->getUsername(); ?>
<!--                    <span class="badge bg-theme">4</span>-->
                </a>
                <ul class="dropdown-menu extended tasks-bar">
                    <div class="notify-arrow notify-arrow-green"></div>
                    <li>
                        <p class="green"><?php echo $this->user->getName(); ?></p>
                    </li>
                    <li>
                        <a href="#" class="top-drop-button">
                            Profile
                        </a>
                    </li>
                    <li>
                        <a href="#" class="top-drop-button">
                            Settings
                        </a>
                    </li>
                    <li>
                        <a href="" class="top-drop-button">
                            Logout
                        </a>
                    </li>
                </ul>
            </li>
            <!-- settings end -->
            <!-- inbox dropdown start-->
            <li id="header_inbox_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-theme">5</span>
                </a>
                <ul class="dropdown-menu extended inbox">
                    <div class="notify-arrow notify-arrow-green"></div>
                    <li>
                        <p class="green">You have 5 new messages</p>
                    </li>
                    <li>
                        <a href="index.html#">
                            <span class="photo"><img alt="avatar" src="assets/img/ui-zac.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Zac Snider</span>
                                    <span class="time">Just now</span>
                                    </span>
                                    <span class="message">
                                        Hi mate, how is everything?
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <span class="photo"><img alt="avatar" src="assets/img/ui-divya.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Divya Manian</span>
                                    <span class="time">40 mins.</span>
                                    </span>
                                    <span class="message">
                                     Hi, I need your help with this.
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <span class="photo"><img alt="avatar" src="assets/img/ui-danro.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Dan Rogers</span>
                                    <span class="time">2 hrs.</span>
                                    </span>
                                    <span class="message">
                                        Love your new Dashboard.
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">
                            <span class="photo"><img alt="avatar" src="assets/img/ui-sherman.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Dj Sherman</span>
                                    <span class="time">4 hrs.</span>
                                    </span>
                                    <span class="message">
                                        Please, answer asap.
                                    </span>
                        </a>
                    </li>
                    <li>
                        <a href="index.html#">See all messages</a>
                    </li>
                </ul>
            </li>
            <!-- inbox dropdown end -->
        </ul>
        <!--  notification end -->
    </div>
<!--    <div class="top-menu" ng-controller="logoutController">-->
<!--        <ul class="nav pull-right top-menu">-->
<!--            <li>-->
<!--                <button class="logout" ng-click="logout()">Logout</button>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->
</header>
<!--header end-->

<!--<div ng-controller="logoutController">
<div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;">
    <a href='#'><?php /*echo $user->getUsername(); */?> </a>
    <button class="btn btn-danger square-btn-adjust" ng-click="logout()">Logout</button> </div>

</div>-->