<!--header start-->
<header class="header black-bg">
    <!--logo start-->
    <a href="<?php echo $this->url('judge/default', array('action' => 'index')); ?>" style='font-weight: bold; ?>' class="logo"><span style="font-size:36px;color:white;font-weight:bold">J</span>udgy <span style="font-size:36px;color:white;font-weight:bold">H</span>acker</a>
    <!--logo end-->
    <div class="nav notify-row pull-right" style="margin-right: 100px"id="top_menu">
        <?php if ($user): ?>
        <!--  notification start -->
        <ul class="nav top-menu" ng-init="alertsCount=<?php echo $notificationsCount; ?>" ng-controller="alertsController">

            <!-- inbox dropdown start-->
            <li id="header_inbox_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="javascript: ;" ng-click="markViewed()">
                    <i class="fa fa-bell-o"></i>
                    <span class="badge bg-theme" ng-show="alertsCount>0 && alertsView==false">{{alertsCount}}</span>
                </a>
                <ul class="dropdown-menu extended inbox dropdown-menu-right">
                    <div class="notify-arrow notify-arrow-green"></div>
                    <?php if ($notifications): ?>
                        <?php foreach ($notifications as $notification): ?>
                            <li class="<?php echo $notification->getCssClass(); ?>">
                                <a href="<?php echo $notification->getLink(); ?>">
                                    <span class="message">
                                        <?php echo $notification->getMessage(); ?>
                                    </span>
                                </a>
                            </li>
                        <?php endforeach ?>
                        <li>
                            <a href="<?php echo $this->url('notifications-view'); ?>">See all notifications</a>
                        </li>
                    <?php else: ?>
                        <li>
                            <p style="min-height: 70px;">No notifications</p>
                        </li>
                    <?php endif ?>

                </ul>
            </li>
            <!-- inbox dropdown end -->
            <!-- settings start -->
            <li class="dropdown" ng-controller="logoutController">
                <a data-toggle="dropdown" class="dropdown-toggle" href="<?php echo $this->url('profile/id', array('id' => (string)$user->getId())); ?>">
                    <img src="<?php echo $this->basePath(); ?>/img/anonymous.jpg" class="img-circle" width="24px">
                    <?php echo $this->user->getUsername(); ?>
                    <!--                    <span class="badge bg-theme">4</span>-->
                </a>
                <ul class="dropdown-menu extended tasks-bar dropdown-menu-right">
                    <div class="notify-arrow notify-arrow-green"></div>
                    <li>
                        <a href="<?php echo $this->url('profile/id', array('id' => (string)$user->getId())); ?>" class="top-drop-button">
                            Profile
                        </a>
                    </li>
                    <li>
                        <a href="#" class="top-drop-button">
                            Settings
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" ng-click="logout(); " class="top-drop-button">
                            Logout
                        </a>
                    </li>
                </ul>
            </li>
            <!-- settings end -->
        </ul>
        <!--  notification end -->
        <?php else: ?>
            <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>" class="btn btn-primary">Sign In</a>
            <a href="<?php echo $this->url('judge/default', array('action' => 'register')); ?>" class="btn btn-primary">Sign Up</a>
        <?php endif ?>
    </div>
<!--    <div class="top-menu" ng-controller="logoutController">-->
<!--        <ul class="nav pull-right top-menu">-->
<!--            <li>-->
<!--                <button class="logout" ng-click="logout()">Logout</button>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->
</header>
<!--header end-->

<!--<div ng-controller="logoutController">
<div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;">
    <a href='#'><?php /*echo $user->getUsername(); */?> </a>
    <button class="btn btn-danger square-btn-adjust" ng-click="logout()">Logout</button> </div>

</div>-->