<div class="row">
    <div class="col-md-12">
        <h2><?php echo $problem->getTitle(); ?></h2>
        <?php foreach ($problem->getTags() as $tag): ?>
            <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('misc/default', array('action' => 'problems'), array('query' => array('tag' => (string)$tag->getText()))); ?>">
                            <span class="">
                                <?php echo $tag->getRealText(); ?>
                            </span>
            </a>
        <?php endforeach ?>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="alert alert-warning">
            <i class="fa fa-users"></i> &nbsp; Attempted by <?php echo $problem->getAttempts(); ?> user(s).
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="alert alert-success">
            <i class="fa fa-check"></i> &nbsp; Solved by <?php echo $problem->getSolved(); ?> user(s).
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="alert alert-info">
            <i class="fa fa-bar-chart-o"></i> &nbsp; Points: <?php echo $problem->getDifficulty(); ?>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-6">
        <div class="alert alert-warning">
            <i class="fa fa-star-half-o"></i> &nbsp; Average rating: <?php echo $problem->getRating(); ?>
        </div>
    </div>
</div>

<?php if ($loggedIn): ?>
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-6">
    <span>Rate problem:</span>
    <span ng-controller="miscProblemRatingController">
        <rating ng-model="rate" max="max" state-on="'fa fa-star fa-2x'" state-off="'fa fa-star-o fa-2x'" readonly="isReadonly" on-hover="hoveringOver(value)" on-leave="overStar = null"></rating>
    </span>
    </div>
</div>
<?php endif ?>

<hr />

<problem-statement ng-transclude><?php echo $problem->getDescription(); ?></problem-statement>

<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php elseif ($submission && $submission->getSolved()): ?>
    <div class="panel panel-primary text-center no-boder bg-color-green">
        <div class="panel-body">
            You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt(s)</strong>.
        </div>
    </div>
<?php else: ?>
<div ng-controller="submitMiscSolutionController">
    <div class="panel panel-primary text-center no-border bg-color-green" ng-show="correctSolution === true">
        <div class="panel-body">
            Congratulations! This is a correct solution.
        </div>
    </div>

    <div class="panel panel-primary text-center no-boder bg-color-red" ng-show="correctSolution === false">
        <div class="panel-body">
            Sorry, but this is not a correct solution.
        </div>
    </div>

    <div class="row" ng-show="correctSolution !== true">
        <div class="col-md-12">
            <form role="form">
                <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                <div class="form-group">
                    <label>Answer</label>
                    <input ng-model="answer" class="form-control" placeholder="Answer" required>
                </div>
                <div class="form-group">
                    <button class="btn btn-success square-btn-adjust" ng-click="submit()">Submit</button>
                </div>
            </form>
        </div>
    </div>

</div>

<?php endif ?>