<div class="row">
    <div class="col-md-12">
        <h2>Misc questions</h2>
    </div>
</div>


    <?php /** @var \Judge\Document\MiscProblem $problem */ ?>
    <?php foreach ($problems as $problem): ?>
        <div class="col-lg-4 col-md-4 col-sm-4 mb">
            <a href="<?php echo $this->url('misc/problem', array('id' => $problem->getId())); ?>">
                <div class="content-panel pn">
                    <div id="blog-bg">
    <!--                    <div class="badge badge-popular">POPULAR</div>-->
                        <div class="blog-title"><?php echo $problem->getTitle(); ?></div>
                    </div>
                    <div class="blog-text">
                        <div>
                            <?php foreach ($problem->getTags() as $tag): ?>
                                <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('misc/default', array('action' => 'problems'), array('query' => array('tag' => (string)$tag->getText()))); ?>">
                                <span class="">
                                    <?php echo $tag->getRealText(); ?>
                                </span>
                                </a>
                            <?php endforeach ?>
                        </div>
                        <?php if ($problem->getUserSubmission() && $problem->getUserSubmission()->getSolved()): ?>
                            <div class="panel panel-primary text-center no-boder bg-color-green">
                                <div class="panel-body">
                                    You already solved this problem on <strong><?php echo $problem->getUserSubmission()->getDateSolved() * 1000; ?></strong> using <strong><?php echo $problem->getUserSubmission()->getAttempts(); ?> attempt(s)</strong>.
                                </div>
                            </div>
                        <?php else: ?>

                        <?php endif ?>
                    </div>
                </div>
            </a>
        </div><!-- /col-md-4-->
    <?php endforeach ?>
