<div class="row">
    <div class="col-md-12">
        <h2>Misc questions</h2>
    </div>
</div>

<table class="table table-hover table-bordered">
    <thead>
    <tr>
        <th>Title</th>
        <th>Difficulty</th>
        <th>Solved</th>
        <th>Attempts</th>
        <th>Rating</th>
    </tr>
    </thead>
    <?php /** @var \Judge\Document\MiscProblem $problem */ ?>
    <?php foreach ($problems as $problem): ?>
        <tr class="<?php echo $problem->getUserSubmission() ? ($problem->getUserSubmission()->getSolved() ? 'success' : 'warning') : ''; ?>">
            <td>
                <a class="problem-title" style="" href="<?php echo $this->url('misc/problem', array('id' => (string)$problem->getId())); ?>">
                    <?php echo $problem->getTitle(); ?>
                </a>
                <div>
                    <?php foreach ($problem->getTags() as $tag): ?>
                        <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('misc/default', array('action' => 'problems'), array('query' => array('tag' => (string)$tag->getText()))); ?>">
                            <span class="">
                                <?php echo $tag->getRealText(); ?>
                            </span>
                        </a>
                    <?php endforeach ?>
                </div>
            </td>
            <td><?php echo (int)$problem->getDifficulty(); ?></td>
            <td><?php echo (int)$problem->getSolved(); ?></td>
            <td><?php echo (int)$problem->getAttempts(); ?></td>
            <td><?php echo (float)$problem->getRating(); ?></td>
        </tr>
    <?php endforeach ?>
</table>