<div class="row">
    <div class="col-md-12">
        <h2>Algorithms scoreboard</h2>
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Score</th>
    </tr>
    </thead>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?php echo $user->getUsername(); ?></td>
            <td><?php echo $user->getName(); ?></td>
            <td><?php echo $user->getScore(); ?></td>
        </tr>
    <?php endforeach ?>
</table>