<div ng-controller="loginController">
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign in</h3>
                </div>
                <div class="panel-body">
                    <form role="form">

                        <div class="form-group">
                            <input ng-model="username" type="username" name="username" id="username" class="form-control input-sm" placeholder="Username">
                        </div>

                        <div class="form-group">
                            <input ng-model="password" type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
                        </div>
                        <button class="btn btn-info btn-block" ng-click="login()">Sign in</button>
                        <p style="font-size:12px">Don't have an account? <a href="#">Sign up</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
