<div ng-controller="registerController" name="registerForm">
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please sign up for Judgy <small>It's free & simple!</small></h3>
                </div>
                <div class="panel-body">
                    <form role="form">
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="text" ng-model="user.firstName" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name" required>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input type="text" ng-model="user.lastName" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name" required>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <input ng-model="user.username" type="text" name="username" id="username" class="form-control input-sm" placeholder="Username" required>
                        </div>

                        <div class="form-group">
                            <input ng-model="user.email" type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address" required>
                        </div>

                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input ng-model="user.password" type="password" name="password" id="password" class="form-control input-sm" placeholder="Password" required>
                                </div>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                                <div class="form-group">
                                    <input ng-model="user.passwordConfirmation" type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password" required>
                                </div>
                            </div>
                        </div>
                        <div class="notification-wrong"  ng-show="registrationError !== false"><span class="message">{{ registrationError }} </span></div>
                        <button class="btn btn-info btn-block" ng-click="register()" ng-disabled="(user.password != user.passwordConfirmation)">Sign Up</button>

                        <p style="font-size:12px">Already have an account? <a href="#">Sign in</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


