<div class="row">
    <div class="col-md-12">
        <h2><?php echo $user->getUsername(); ?></h2>
        <hr/>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6" style="text-align: center">
                <img src="<?php echo $this->basePath(); ?>/img/anonymous.jpg" class="img-circle" width="200">
            </div>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <td>Username:</td>
                        <td><?php echo $user->getUsername(); ?></td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td><?php echo $user->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>Algorithm problems solved:</td>
                        <td><?php echo $user->getAlgorithmSolved(); ?></td>
                    </tr>
                    <tr>
                        <td>Misc solved:</td>
                        <td><?php echo $user->getMiscSolved(); ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Algorithm activity:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Problem</th>
                    <th>Language</th>
                    <th>Status</th>
                </tr>
            </thead>
            <?php /** @var \Judge\Document\AlgorithmUserSubmission $submission */ ?>
            <?php foreach ($algorithmSubmissions as $submission): ?>
                <tr class="<?php echo $submission->getClassFromStatus(); ?>">
                    <td>{{<?php echo $submission->getTimeCreated()->format('U') * 1000; ?> | date: 'medium'}}</td>
                    <td><?php echo $submission->getProblemId(); ?></td>
                    <td><?php echo $submission->getLanguage(); ?></td>
                    <td><?php echo $submission->getStringFromStatus(); ?></td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
    <div class="col-md-6">
        <h3>Misc activity: </h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Problem</th>
                    <th>Correct</th>
                </tr>
            </thead>
            <?php /** @var \Judge\Document\MiscUserSubmission $submission */ ?>
            <?php foreach ($miscSubmissions as $submission): ?>
                <tr class="<?php echo $submission->getSolved() ? 'success' : 'danger'; ?>">
                    <td>{{ <?php echo $submission->getTimeCreated()->format('U') * 1000; ?> | date : 'medium'}}</td>
                    <td><?php echo $submission->getProblemId(); ?></td>
                    <td><?php echo $submission->getSolved() ? 'Yes' : 'No'; ?></td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>
