<div class="row">
    <div class="col-md-12">
        <h2><?php echo $user->getUsername(); ?></h2>
        <hr/>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-6" style="text-align: center">
                <img src="<?php echo $this->basePath(); ?>/img/anonymous.jpg" class="img-circle" width="200">
            </div>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <td>Username:</td>
                        <td><?php echo $user->getUsername(); ?></td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td><?php echo $user->getName(); ?></td>
                    </tr>
                    <tr>
                        <td>Algorithm problems solved:</td>
                        <td><?php echo $user->getAlgorithmSolved(); ?></td>
                    </tr>
                    <tr>
                        <td>Misc solved:</td>
                        <td><?php echo $user->getMiscSolved(); ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Algorithm activity:</h3>
        <?php echo $this->algorithmSubmissionsList; ?>
    </div>
    <div class="col-md-6">
        <h3>Misc activity: </h3>
        <?php echo $this->miscSubmissionsList; ?>
    </div>
</div>
