<div class="row">
    <div class="col-md-12">
        <h2><?php echo htmlspecialchars($user->getName()); ?> (@<?php echo $user->getUsername(); ?>)</h2>
        <hr/>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-6" style="text-align: center">
                <img src="http://www.gravatar.com/avatar/<?php echo md5(strtolower($user->getEmail())); ?>?s=200&d=//judgyhacker.net/img/anonymous.jpg" class="img-circle" width="200">
                <?php if ($currentUser && $currentUser->getId() == $user->getId()): ?>
                    <div><small style="border: 1px #bdbdbd solid; padding: 3px;">Using <a href="//gravatar.com">Gravatar</a></small></div>
                <?php endif ?>
            </div>
            <div class="col-md-6">
                <table class="table">
                    <tr>
                        <td>Username:</td>
                        <td><?php echo $user->getUsername(); ?></td>
                    </tr>
                    <tr>
                        <td>Name:</td>
                        <td><?php echo htmlspecialchars($user->getName()); ?></td>
                    </tr>
                    <tr>
                        <td>Algorithm problems solved:</td>
                        <td><?php echo (int)$user->getAlgorithmSolved(); ?></td>
                    </tr>
                    <tr>
                        <td>Misc solved:</td>
                        <td><?php echo (int)$user->getMiscSolved(); ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Algorithm activity:</h3>
        <?php echo $this->algorithmSubmissionsList; ?>
    </div>
    <div class="col-md-6">
        <h3>Misc activity: </h3>
        <?php echo $this->miscSubmissionsList; ?>
    </div>
</div>
