<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-advance table-hover">
            <thead>
            <tr>
                <th style="width: 155px;">Date</th>
                <th>Lang</th>
                <th>Passed</th>
                <th>Score</th>
                <th>Status</th>
                <th>&nbsp;</th>
            </tr>
            </thead>

            <?php foreach ($submissions as $algorithmSubmission): ?>
                <tr class="<?php echo $algorithmSubmission->getClassFromStatus(); ?>">
                    <td>{{<?php echo $algorithmSubmission->getTimeCreated()->getTimestamp() * 1000; ?> | date:'short'}}</td>
                    <td><?php echo $algorithmSubmission->getLanguage(); ?></td>
                    <td><?php echo (string)(int)$algorithmSubmission->getSolvedCases() . '/' . (string)(int)$algorithmSubmission->getTotalCases(); ?></td>
                    <td><?php echo round((float)$algorithmSubmission->getScore(), 3); ?></td>
                    <td><?php echo $algorithmSubmission->getStringFromStatus(); ?></td>
                    <td>
                        <?php if ($user && $user->getId() == $algorithmSubmission->getUserId()): ?>
                        <button class="btn btn-default" href="javascript: ;" data-toggle="modal" data-target="#stdout-<?php echo (string)$algorithmSubmission->getId(); ?>">Response</button>

                        <div class="modal fade" id="stdout-<?php echo (string)$algorithmSubmission->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title" id="myModalLabel">Resonse</h4>
                                    </div>
                                    <div class="modal-body">
                                        <?php echo $algorithmSubmission->getMessage(); ?>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button class="btn btn-default" href="javascript: ;" data-toggle="modal" data-target="#source-<?php echo (string)$algorithmSubmission->getId(); ?>">Source</button>

                        <div class="modal fade" id="source-<?php echo (string)$algorithmSubmission->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title" id="myModalLabel">Source</h4>
                                    </div>
                                    <div class="modal-body">
                                        <pre><?php echo htmlspecialchars($algorithmSubmission->getSource()); ?></pre>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>