<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th style="width: 155px;">Time</th>
                <th>Problem</th>
                <th style="width: 75px;">Correct</th>
                <th style="">Score</th>
            </tr>
            </thead>
            <?php /** @var \Judge\Document\MiscUserSubmission $submission */ ?>
            <?php foreach ($submissions as $submission): ?>
                <tr class="<?php echo $submission->getSolved() ? 'success' : 'danger'; ?>">
                    <td>{{ <?php echo $submission->getTimeCreated()->format('U') * 1000; ?> | date : 'short'}}</td>
                    <td><a href="<?php echo $this->url('problems-view/default', array('action' => 'problem', 'type' => $problemsLookup[$submission->getProblemId()]->getType(), 'id' => $submission->getProblemId())); ?>"><?php echo $problemsLookup[$submission->getProblemId()]->getTitle(); ?></a></td>
                    <td><?php echo $submission->getSolved() ? 'Yes' : 'No'; ?></td>
                    <td><?php echo round((float)$submission->getScore(), 3); ?></td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>