<?php if ($user): ?>
    <div class="row">
        <div class="col-md-12">
            <span ng-controller="problemRatingController" ng-init="<?php echo $rating ? 'rate=' . $rating->getValue() : ''; ?>;
                                 targetType='<?php echo addslashes(get_class($problem)); ?>';
                                 targetId='<?php echo (string)$problem->getId(); ?>';
                                 rateMessage='<?php echo $rating ? 'Your rating: ' : 'Rate problem: '; ?>';
                                 starsColor='<?php echo $rating ? 'darkgreen' : 'darkorange' ?>';"

                    style="color: {{ starsColor }}">
                <h4 style="display: inline-block">{{ rateMessage }}</h4>
                <rating
                        style="display: inline-block"
                        ng-model="rate"
                        max="max"
                        state-on="'fa fa-star fa-2x'"
                        state-off="'fa fa-star-o fa-2x'"
                        readonly="isReadonly"
                        on-hover="hoveringOver(value)"
                        on-leave="overStar = null">
                </rating>
            | <span style="color: black;font-size: 18px; display: inline-block">Problem rating: {{ rate }}</span>
            </span>
        </div>
    </div>
<?php endif ?>