<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class JudgeDocumentNotificationHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="object_id") */
        if (isset($data['uid'])) {
            $value = $data['uid'];
            $return = (string) $value;
            $this->class->reflFields['userId']->setValue($document, $return);
            $hydratedData['userId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['message'])) {
            $value = $data['message'];
            $return = (string) $value;
            $this->class->reflFields['message']->setValue($document, $return);
            $hydratedData['message'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['htmlMessage'])) {
            $value = $data['htmlMessage'];
            $return = (string) $value;
            $this->class->reflFields['cssClass']->setValue($document, $return);
            $hydratedData['cssClass'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['link'])) {
            $value = $data['link'];
            $return = (string) $value;
            $this->class->reflFields['link']->setValue($document, $return);
            $hydratedData['link'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['icon'])) {
            $value = $data['icon'];
            $return = (string) $value;
            $this->class->reflFields['icon']->setValue($document, $return);
            $hydratedData['icon'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['read'])) {
            $value = $data['read'];
            $return = (bool) $value;
            $this->class->reflFields['read']->setValue($document, $return);
            $hydratedData['read'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['tc'])) {
            $value = $data['tc'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } elseif ($value instanceof \DateTime) { $return = $value; } else { $return = new \DateTime($value); }
            $this->class->reflFields['timeCreated']->setValue($document, clone $return);
            $hydratedData['timeCreated'] = $return;
        }

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }
        return $hydratedData;
    }
}