<h2 style="margin-bottom: 0px !important"><?php echo $problem->getTitle(); ?>
    <?php if ($user && $user->getIsAdmin()): ?>
        <div class="pull-right">
            <a class="" href="<?php echo $this->url('problems-view/default', array('action' => 'submit', 'type' => 'algorithm', 'id' => (string)$problem->getId())); ?>"><i class="fa fa-pencil"></i></a>
            <a class="" href="#"><i class="fa fa-remove"></i></a>
        </div>
    <?php endif ?>
</h2>
<?php if ($problem->getTags()): ?>
    <?php foreach ($problem->getTags() as $tag): ?>
        <span><?php echo $tag; ?></span>
    <?php endforeach ?>
<?php endif ?>
<div class="panel panel-primary bg-color-gray nobordera style="margin-top: 20px">
    <div class="panel-body">
        <?php echo $problem->getDescription(); ?>
    </div>
</div>
<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php else: ?>

    <div ng-controller="submitAlgorithmSolutionController">
        <div class="panel panel-primary text-center no-border" ng-show="submitDone === true && submissionError === true">
            <div class="panel-body">
                Error occurred while sending your solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-border" ng-show="submitDone === true && submissionError !== true">
            <div class="panel-body">
                Thank you. Your submission will be processed very soon.
            </div>
        </div>

        <?php if ($cooldownLeft <= 0): ?>
            <div class="row" ng-show="submitDone !== true">
                <div class="col-md-12">
                    <form role="form">
                        <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <select class="form-control" ng-model="solution.language"
                                                    ng-options="language.langId as language.langName for language in languages"
                                                    required>
                                                <option value="">Select Language</option>
                                            </select>
                                            <span ng-show="myForm.service_id.$error.required">Select language</span>
                                        </div>
                                        <div class="form-group col-md-9" style="margin-top: 6px">
                                            <input type="file" ng-file-select="onFileSelect($files)" ng-model="solution.file" required="">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-success square-btn-adjust" ng-click="submitSolution()">Submit</button>
                                    </div>
                                </div>
                            </div>

                    </form>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-primary text-center no-boder">
                <div class="panel-body">
                    You can't resubmit answer to this question for another <?php echo $cooldownLeft; ?> seconds.
                </div>
            </div>
        <?php endif ?>
        <?php if ($submission && $submission->getSolved()): ?>
            <div class="panel panel-primary text-center no-boder">
                <div class="panel-body">
                    You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt<?php echo $submission->getAttempts() === 1 ? "" : "s"; ?></strong>.
                </div>
            </div>
        <?php elseif ($submission): ?>
            <div class="pull-right">
                You already tried  to solve this problem <strong><?php echo (string)$submission->getAttempts() . ' ' . (($submission->getAttempts() > 1) ? 'times' : 'time'); ?></strong>.
            </div>
        <?php endif ?>
    </div>
<?php endif ?>

<?php if ($loggedIn): ?>
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-6">
            <span ng-controller="problemRatingController" ng-init="<?php echo $rating ? 'rate=' . $rating->getValue() : ''; ?>;
                                 targetType='<?php echo addslashes(get_class($problem)); ?>';
                                 targetId='<?php echo (string)$problem->getId(); ?>';
                                 rateMessage='<?php echo $rating ? 'Your rating: ' : 'Rate problem: '; ?>';
                                 starsColor='<?php echo $rating ? 'darkgreen' : 'darkorange' ?>';"

                    style="color: {{ starsColor }}">
                <h4 style="display: inline-block">{{ rateMessage }}</h4>
                <rating
                        ng-model="rate"
                        max="max"
                        state-on="'fa fa-star fa-2x'"
                        state-off="'fa fa-star-o fa-2x'"
                        readonly="isReadonly"
                        on-hover="hoveringOver(value)"
                        on-leave="overStar = null">
                </rating>
            </span>
        </div>
    </div>
<?php endif ?>
<div class="row mtbox">
    <div class="col-md-2 col-sm-2 col-md-offset-2 box0">
        <div class="box1">
            <i class="fa fa-edit fa-2x"></i>
            <h3><?php echo (int)$problem->getAttempts(); ?></h3>
        </div>
        <p>Number of users attempted to answer this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-check fa-2x"></i>
            <h3><?php echo (int)$problem->getSolved(); ?></h3>
        </div>
        <p>Number of users successfully solved this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-question-circle fa-2x"></i>
            <h3><?php echo (int)$problem->getDifficulty(); ?></h3>
        </div>
        <p>Question difficulty. More difficult problems you solve more points you get. Fair enough, isn't it?</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-star-half-empty fa-2x"></i>
            <h3><?php echo (float)$problem->getRating(); ?></h3>
        </div>
        <p>Average question rating.</p>
    </div>
</div>
<?php if ($loggedIn): ?>
    <h2>Past submissions:</h2>
    <table class="table table-striped table-advance table-hover">
        <thead>
            <tr>
                <th>Date</th>
                <th>Lang</th>
                <th>Passed</th>
                <th>Score</th>
                <th>Status</th>
                <th>&nbsp;</th>
            </tr>
        </thead>

        <?php foreach ($algorithmSubmissions as $algorithmSubmission): ?>
            <tr class="<?php echo $algorithmSubmission->getClassFromStatus(); ?>">
                <td>{{<?php echo $algorithmSubmission->getTimeCreated()->getTimestamp() * 1000; ?> | date:'medium'}}</td>
                <td><?php echo $algorithmSubmission->getLanguage(); ?></td>
                <td><?php echo (string)(int)$algorithmSubmission->getSolvedCases() . '/' . (string)(int)$algorithmSubmission->getTotalCases(); ?></td>
                <td><?php echo $algorithmSubmission->getScore(); ?></td>
                <td><?php echo $algorithmSubmission->getStringFromStatus(); ?></td>
                <td>
                    <button class="btn btn-default" href="javascript: ;" data-toggle="modal" data-target="#stdout-<?php echo (string)$algorithmSubmission->getId(); ?>">Response</button>

                    <div class="modal fade" id="stdout-<?php echo (string)$algorithmSubmission->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="myModalLabel">Resonse</h4>
                                </div>
                                <div class="modal-body">
                                    <?php echo $algorithmSubmission->getMessage(); ?>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-default" href="javascript: ;" data-toggle="modal" data-target="#source-<?php echo (string)$algorithmSubmission->getId(); ?>">Source</button>

                    <div class="modal fade" id="source-<?php echo (string)$algorithmSubmission->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="myModalLabel">Source</h4>
                                </div>
                                <div class="modal-body">
                                    <pre><?php echo htmlspecialchars($algorithmSubmission->getSource()); ?></pre>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>
