<div class="white-panel pn">
    <div class="white-header">
        <h1><?php echo $problem->getTitle(); ?></h1>
        <?php foreach ($problem->getTags() as $tag): ?>
            <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => 'misc'), array('query' => array('tag' => $tag->getText()))); ?>">
                            <span class="">
                                <?php echo $tag->getRealText(); ?>
                            </span>
            </a>
        <?php endforeach ?>
    </div>
    <div class="row">
        <?php echo $problem->getDescription(); ?>
    </div>
</div>
<br />
<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php else: ?>

    <div ng-controller="submitAlgorithmSolutionController">
        <div class="panel panel-primary text-center no-border bg-color-green" ng-show="correctSolution === true">
            <div class="panel-body">
                Congratulations! This is a correct solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-boder bg-color-red" ng-show="correctSolution === false">
            <div class="panel-body">
                Sorry, but this is not a correct solution.
            </div>
        </div>

        <div class="row" ng-show="correctSolution !== true">
            <div class="col-md-12">
                <form role="form">
                    <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Submission
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="form-group col-md-3">
                                        <select class="form-control" ng-model="solution.language"
                                                ng-options="language.langId as language.langName for language in languages"
                                                required>
                                            <option value="">Select Language</option>
                                        </select>
                                        <span ng-show="myForm.service_id.$error.required">Select service</span>
                                    </div>
                                    <div class="form-group col-md-9" style="margin-top: 6px">
                                        <input type="file" ng-file-select="onFileSelect($files)" ng-model="solution.file" required="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    <div class="form-group">
                        <button class="btn btn-success square-btn-adjust" ng-click="submitSolution()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <?php if ($submission && $submission->getSolved()): ?>
            <div class="panel panel-primary text-center no-boder bg-color-green">
                <div class="panel-body">
                    You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt<?php echo $submission->getAttempts() === 1 ? "" : "s"; ?></strong>.
                </div>
            </div>
        <?php elseif ($submission): ?>
            <div class="panel panel-primary text-center no-boder bg-color-orange">
                <div class="panel-body">
                    You already tried  to solve this problem <?php echo (string)$submission->getAttempts() . ' ' . (($submission->getAttempts() > 1) ? 'times' : 'time'); ?>.
                </div>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>
<hr />

<?php if ($loggedIn): ?>
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-6">
            <span>Rate problem:</span>
    <span ng-controller="miscProblemRatingController">
        <rating ng-model="rate" max="max" state-on="'fa fa-star fa-2x'" state-off="'fa fa-star-o fa-2x'" readonly="isReadonly" on-hover="hoveringOver(value)" on-leave="overStar = null"></rating>
    </span>
        </div>
    </div>
<?php endif ?>
<div class="row mtbox">
    <div class="col-md-2 col-sm-2 col-md-offset-2 box0">
        <div class="box1">
            <i class="fa fa-edit fa-2x"></i>
            <h3><?php echo (int)$problem->getAttempts(); ?></h3>
        </div>
        <p>Number of users attempted to answer this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-check fa-2x"></i>
            <h3><?php echo (int)$problem->getSolved(); ?></h3>
        </div>
        <p>Number of users successfully solved this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-question-circle fa-2x"></i>
            <h3><?php echo (int)$problem->getDifficulty(); ?></h3>
        </div>
        <p>Question difficulty. More difficult problems you solve more points you get. Fair enough, isn't it?</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-star-half-empty fa-2x"></i>
            <h3><?php echo (float)$problem->getRating(); ?></h3>
        </div>
        <p>Average question rating.</p>
    </div>
</div>

<h2>Past submissions:</h2>
<table class="table table-striped table-advance table-hover">
    <thead>
        <tr>
            <th>Date</th>
            <th>Lang</th>
            <th>Passed</th>
            <th>Score</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>

    <?php foreach ($algorithmSubmissions as $algorithmSubmission): ?>
        <tr class="<?php echo $algorithmSubmission->getClassFromStatus(); ?>">
            <td>{{<?php echo $algorithmSubmission->getTimeCreated()->getTimestamp() * 1000; ?> | date:'medium'}}</td>
            <td><?php echo $algorithmSubmission->getLanguage(); ?></td>
            <td><?php echo (string)(int)$algorithmSubmission->getSolvedCases() . '/' . (string)(int)$algorithmSubmission->getTotalCases(); ?></td>
            <td><?php echo $algorithmSubmission->getScore(); ?></td>
            <td><?php echo $algorithmSubmission->getStringFromStatus(); ?></td>
            <td>
                <button class="btn btn-default" href="javascript: ;" data-toggle="modal" data-target="#stdout-<?php echo (string)$algorithmSubmission->getId(); ?>">Response</button>

                <div class="modal fade" id="stdout-<?php echo (string)$algorithmSubmission->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title" id="myModalLabel">Resonse</h4>
                            </div>
                            <div class="modal-body">
                                <?php echo $algorithmSubmission->getProcessedMessage(); ?>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
</table>
