<?php echo $this->problemStatement; ?>

<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php else: ?>

    <div ng-controller="submitAlgorithmSolutionController">
        <div class="panel panel-primary text-center no-border" ng-show="submitDone === true && submissionError === true">
            <div class="panel-body">
                Error occurred while sending your solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-border" ng-show="submitDone === true && submissionError !== true">
            <div class="panel-body">
                Thank you. Your submission will be processed very soon.
            </div>
        </div>

        <?php if ($cooldownLeft <= 0): ?>
            <div class="row" ng-show="submitDone !== true">
                <div class="col-md-12">
                    <form role="form">
                        <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="form-group col-md-3">
                                            <select class="form-control" ng-model="solution.language"
                                                    ng-options="language.langId as language.langName for language in languages"
                                                    required>
                                                <option value="">Select Language</option>
                                            </select>
                                            <span ng-show="myForm.service_id.$error.required">Select language</span>
                                        </div>
                                        <div class="form-group col-md-9" style="margin-top: 6px">
                                            <input type="file" ng-file-select="onFileSelect($files)" ng-model="solution.file" required="">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-success square-btn-adjust" ng-click="submitSolution()">Submit</button>
                                    </div>
                                </div>
                            </div>

                    </form>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-primary text-center no-boder">
                <div class="panel-body">
                    You can't resubmit answer to this question for another <?php echo $cooldownLeft; ?> seconds.
                </div>
            </div>
        <?php endif ?>
        <?php if ($submission && $submission->getSolved()): ?>
            <div class="panel panel-primary text-center no-boder">
                <div class="panel-body">
                    You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt<?php echo $submission->getAttempts() === 1 ? "" : "s"; ?></strong>.
                </div>
            </div>
        <?php elseif ($submission): ?>
            <div class="pull-right">
                You already tried  to solve this problem <strong><?php echo (string)$submission->getAttempts() . ' ' . (($submission->getAttempts() > 1) ? 'times' : 'time'); ?></strong>.
            </div>
        <?php endif ?>
    </div>
<?php endif ?>

<?php echo $this->rateProblem; ?>
<?php echo $this->problemMeta; ?>

<?php if ($loggedIn): ?>
    <h2>Past submissions:</h2>
    <?php echo $this->pastSubmissionsList; ?>
<?php endif ?>
