<?php echo $this->problemStatement; ?>

<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php elseif ($submission && $submission->getSolved()): ?>
    <div class="panel panel-primary text-center no-boder bg-color-green">
        <div class="panel-body">
            You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt<?php echo $submission->getAttempts() === 1 ? "" : "s"; ?></strong>.
        </div>
    </div>
<?php else: ?>
    <div ng-controller="submitMiscSolutionController">
        <div class="panel panel-primary text-center no-border bg-color-green" ng-show="submissionError === false && correctSolution === true">
            <div class="panel-body">
                Congratulations! This is a correct solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-boder bg-color-orange" ng-show="submissionError === false && correctSolution === false">
            <div class="panel-body">
                Sorry, but this is not a correct solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-boder bg-color-red" ng-show="submissionError === true">
            <div class="panel-body">
                {{ errorMessage }}
            </div>
        </div>
        <?php if ($cooldownLeft <= 0): ?>
            <div class="row" ng-show="submitDone !== true && correctSolution !== true">
                <div class="col-md-12">
                    <form role="form">
                        <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                        <div class="form-group">
                            <label>Answer</label>
                            <input ng-model="answer" class="form-control" placeholder="Answer" required>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success square-btn-adjust" ng-click="submit()">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-primary text-center no-boder bg-color-red">
                <div class="panel-body">
                    You can't resubmit answer to this question for another <?php echo $cooldownLeft; ?> seconds.
                </div>
            </div>
        <?php endif ?>
        <?php if ($submission): ?>
            <div class="pull-right">
                You already tried  to solve this problem <strong><?php echo (string)$submission->getAttempts() . ' ' . (($submission->getAttempts() > 1) ? 'times' : 'time'); ?></strong>.
            </div>
        <?php endif ?>
    </div>
<?php endif ?>

<?php echo $this->rateProblem; ?>
<?php echo $this->problemMeta; ?>

