<?php if (!$user->getIsAdmin()): ?>
    <div class="panel panel-primary bg-color-blue">
        <div class="panel-body">
            Everybody can submit a question for Judgy. Each question will be reviewed by administrators and posted onto the site.
        </div>
    </div>
<?php endif ?>

<div ng-controller="submitMiscController" ng-init="
            problem.title='<?php echo $problem ? addslashes($problem->getTitle()) : ''; ?>';
            problem.difficulty='<?php echo $problem ? (int)$problem->getDifficulty() : ''; ?>';
            problem.answer='<?php echo $problem ? addslashes($problem->getAnswer()) : ''; ?>';
            problem.tags=<?php echo $problem ? str_replace('"', "'", json_encode($problem->getTags())) : '[]'; ?>;
            problem.id='<?php echo $problem ? (string)$problem->getId() : ''; ?>';
        "
    >
    <div class="panel panel-primary text-center no-boder bg-color-green" ng-show="successfulSubmission === true">
        <div class="panel-body">
            <?php if (!$user->getIsAdmin()): ?>
                Thank you! Your problem has been submitted and it's ready for review.
            <?php else: ?>
                Problem successfully added to the list.
            <?php endif ?>
        </div>
    </div>

    <div class="panel panel-primary text-center no-boder bg-color-red" ng-show="submissionError && successfulSubmission !== true">
        <div class="panel-body">
            {{ submissionError }}
        </div>
    </div>

    <div class="row" ng-show="successfulSubmission !== true">
        <div class="col-md-12">
            <form role="form">
                <div class="form-group">
                    <label>Problem Title</label>
                    <input ng-model="problem.title" class="form-control" placeholder="Title" required>
                </div>
                <div class="form-group">
                    <label>Question</label>
                    <text-angular ng-model="problem.description"><?php echo $problem ? $problem->getDescription() : ''; ?></text-angular>
                </div>
                <div class="form-group">
                    <label>Answer</label>
                    <input ng-model="problem.answer" class="form-control" placeholder="Answer" required>
                </div>

                <div class="form-group">
                    <label>Difficulty</label>
                    <input ng-model="problem.difficulty" class="form-control" placeholder="Difficulty" required>
                </div>

                <div class="form-group">
                    <label>Tags</label>
                    <tags-input ng-model="problem.tags">
                        <auto-complete source="loadTags($query)"></auto-complete>
                    </tags-input>
                </div>
                <div class="form-group">
                    <button class="btn btn-success square-btn-adjust" ng-click="submit()">Submit Problem</button> </div>
        </div>
        </form>
    </div>
</div>
</div>