<div class="white-panel pn">
    <div class="white-header">
        <h4><?php echo $problem->getTitle(); ?></h4>
        <?php if ($problem->getTags()): ?>
            <?php foreach ($problem->getTags() as $tag): ?>
                <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => 'misc'), array('query' => array('tag' => $tag))); ?>">
                                <span class="">
                                    <?php echo $tag; ?>
                                </span>
                </a>
            <?php endforeach ?>
        <?php endif ?>
    </div>
    <div class="row">
        <?php echo $problem->getDescription(); ?>
    </div>
</div>
<br />
<?php if (!$loggedIn): ?>
    <div class="panel panel-primary text-center no-boder bg-color-orange">
        <div class="panel-body">
            You have to <a href="<?php echo $this->url('judge/default', array('action' => 'login')); ?>">sign in</a> to be able to rate or submit your answer.
        </div>
    </div>
<?php elseif ($submission && $submission->getSolved()): ?>
    <div class="panel panel-primary text-center no-boder bg-color-green">
        <div class="panel-body">
            You already solved this problem on <strong>{{<?php echo $submission->getDateSolved()->getTimestamp() * 1000; ?> | date:'medium'}}</strong> using <strong><?php echo $submission->getAttempts(); ?> attempt<?php echo $submission->getAttempts() === 1 ? "" : "s"; ?></strong>.
        </div>
    </div>
<?php else: ?>
    <div ng-controller="submitMiscSolutionController">
        <div class="panel panel-primary text-center no-border bg-color-green" ng-show="submissionError === false && correctSolution === true">
            <div class="panel-body">
                Congratulations! This is a correct solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-boder bg-color-orange" ng-show="submissionError === false && correctSolution === false">
            <div class="panel-body">
                Sorry, but this is not a correct solution.
            </div>
        </div>

        <div class="panel panel-primary text-center no-boder bg-color-red" ng-show="submissionError === true">
            <div class="panel-body">
                {{ errorMessage }}
            </div>
        </div>
        <?php if ($cooldownLeft <= 0): ?>
            <div class="row" ng-show="correctSolution !== true">
                <div class="col-md-12">
                    <form role="form">
                        <input ng-model="id" type="hidden" ng-init="id='<?php echo (string)$problem->getId(); ?>'">
                        <div class="form-group">
                            <label>Answer</label>
                            <input ng-model="answer" class="form-control" placeholder="Answer" required>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success square-btn-adjust" ng-click="submit()">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        <?php else: ?>
            <div class="panel panel-primary text-center no-boder bg-color-red">
                <div class="panel-body">
                    You can't resubmit answer to this question for another <?php echo $cooldownLeft; ?> seconds.
                </div>
            </div>
        <?php endif ?>
        <?php if ($submission): ?>
            <div class="panel panel-primary text-center no-boder bg-color-orange">
                <div class="panel-body">
                    You already tried  to solve this problem <?php echo (string)$submission->getAttempts() . ' ' . (($submission->getAttempts() > 1) ? 'times' : 'time'); ?>.
                </div>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>

<?php if ($loggedIn): ?>
    <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-6">
            <span ng-controller="problemRatingController" ng-init="<?php echo $rating ? 'rate=' . $rating->getValue() : ''; ?>;
                                 targetType='<?php echo addslashes(get_class($problem)); ?>';
                                 targetId='<?php echo (string)$problem->getId(); ?>';
                                 rateMessage='<?php echo $rating ? 'Your rating: ' : 'Rate problem: '; ?>';
                                 starsColor='<?php echo $rating ? 'darkgreen' : 'darkorange' ?>';"

                  style="color: {{ starsColor }}">
                <h4 style="display: inline-block">{{ rateMessage }}</h4>
                <rating
                    ng-model="rate"
                    max="max"
                    state-on="'fa fa-star fa-2x'"
                    state-off="'fa fa-star-o fa-2x'"
                    readonly="isReadonly"
                    on-hover="hoveringOver(value)"
                    on-leave="overStar = null">
                </rating>
            </span>
        </div>
    </div>
<?php endif ?>
<div class="row mtbox">
    <div class="col-md-2 col-sm-2 col-md-offset-2 box0">
        <div class="box1">
            <i class="fa fa-edit fa-2x"></i>
            <h3><?php echo (int)$problem->getAttempts(); ?></h3>
        </div>
        <p>Number of users attempted to answer this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-check fa-2x"></i>
            <h3><?php echo (int)$problem->getSolved(); ?></h3>
        </div>
        <p>Number of users successfully solved this question.</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-question-circle fa-2x"></i>
            <h3><?php echo (int)$problem->getDifficulty(); ?></h3>
        </div>
        <p>Question difficulty. More difficult problems you solve more points you get. Fair enough, isn't it?</p>
    </div>
    <div class="col-md-2 col-sm-2 box0">
        <div class="box1">
            <i class="fa fa-star-half-empty fa-2x"></i>
            <h3><?php echo (float)$problem->getRating(); ?></h3>
        </div>
        <p>Average question rating.</p>
    </div>
</div>