<div class="content-panel">
    <table class="table table-striped table-advance table-hover">
        <h4><i class="fa fa-angle-right"></i> <?php echo $title; ?></h4>
        <hr>
        <thead>
        <tr>
            <th style="width: 65%"> Title</th>
            <th class="hidden-phone"><i class="fa fa-question-circle"></i> Difficulty</th>
            <th><i class="fa fa-check"></i> Solved</th>
            <th><i class=" fa fa-edit"></i> Attempts</th>
            <th><i class=" fa fa-star-half-empty"></i> Rating</th>
        </tr>
        </thead>
        <?php /** @var \Judge\Document\ActiveProblem $problem */ ?>
        <?php foreach ($problems as $problem): ?>
            <tr class="<?php echo $problem->getUserSubmission() ? ($problem->getUserSubmission()->getSolved() ? 'success' : 'warning') : ''; ?>">
                <td>
                    <a class="problem-title" style="" href="<?php echo $this->url('problems-view/default', array('action' => 'problem', 'type' => $type, 'id' => (string)$problem->getId())); ?>">
                        <p><?php echo $problem->getTitle(); ?></p>
                    </a>
                    <div>
                        <?php if ($problem->getTags()): ?>
                            <?php foreach ($problem->getTags() as $tag): ?>
                                <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => $type), array('query' => array('tag' => $tag))); ?>">
                                <span class="">
                                    <?php echo $tag; ?>
                                </span>
                                </a>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>
                </td>
                <td><?php echo (int)$problem->getDifficulty(); ?></td>
                <td><?php echo (int)$problem->getSolved(); ?></td>
                <td><?php echo (int)$problem->getAttempts(); ?></td>
                <td><?php echo (float)$problem->getRating(); ?></td>
            </tr>
        <?php endforeach ?>
    </table>
    <?php if ($numPages > 1): ?>
        <nav>
            <ul class="pagination">
                <li class="<?php echo $currentPage <= 1 ? 'disabled' : ''; ?>">
                    <a href="<?php echo $this->url('problems-view/default', array('type' => $type, 'action' => 'problems'), array('query' => array('page' => $currentPage - 1))); ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <?php for($i=1; $i<=$numPages; $i++): ?>
                    <li class="<?php echo ($i==$currentPage) ? 'active' : ''; ?>">
                        <a href="<?php echo $this->url("problems-view/default", array('type' => $type, 'action' => 'problems'), array('query' => array('page' => $i))); ?>"><?php echo $i; ?></a>
                    </li>
                <?php endfor ?>
                <li class="<?php echo $currentPage >= $numPages ? 'disabled' : ''; ?>">
                    <a href="<?php echo $this->url('problems-view/default', array('type' => $type, 'action' => 'problems'), array('query' => array('page' => $currentPage + 1))); ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif ?>
</div>