<div class="content-panel">
    <table class="table table-striped table-advance table-hover">
        <h4><i class="fa fa-angle-right"></i> <?php echo $title; ?></h4>
        <hr>
        <thead>
        <tr>
            <th> Title</th>
            <th class="hidden-phone"><i class="fa fa-question-circle"></i> Difficulty</th>
            <th><i class="fa fa-check"></i> Solved</th>
            <th><i class=" fa fa-edit"></i> Attempts</th>
            <th><i class=" fa fa-star-half-empty"></i> Rating</th>
        </tr>
        </thead>
        <?php /** @var \Judge\Document\ActiveProblem $problem */ ?>
        <?php foreach ($problems as $problem): ?>
            <tr class="<?php echo $problem->getUserSubmission() ? ($problem->getUserSubmission()->getSolved() ? 'success' : 'warning') : ''; ?>">
                <td>
                    <a class="problem-title" style="" href="<?php echo $this->url('problems-view/default', array('action' => 'problem', 'type' => $type, 'id' => (string)$problem->getId())); ?>">
                        <p><?php echo $problem->getTitle(); ?></p>
                    </a>
                    <div>
                        <?php foreach ($problem->getTags() as $tag): ?>
                            <a class="label label-warning" style="margin:4px;" href="<?php echo $this->url('problems-view/default', array('action' => 'problems', 'type' => $type), array('query' => array('tag' => $tag))); ?>">
                            <span class="">
                                <?php echo $tag; ?>
                            </span>
                            </a>
                        <?php endforeach ?>
                    </div>
                </td>
                <td><?php echo (int)$problem->getDifficulty(); ?></td>
                <td><?php echo (int)$problem->getSolved(); ?></td>
                <td><?php echo (int)$problem->getAttempts(); ?></td>
                <td><?php echo (float)$problem->getRating(); ?></td>
            </tr>
        <?php endforeach ?>
    </table>
</div>