<div class="row">
    <div class="col-md-12">
        <h2><?php echo $title; ?></h2>
        <hr/>
    </div>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th style="width: 30%">Username</th>
        <th style="width: 40%">Name</th>
        <th style="width: 15%">Solved</th>
        <th style="width: 15%">Score</th>
    </tr>
    </thead>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><a href='<?php echo $this->url('profile/id', array('id' => (string)$user->getId())); ?>'><?php echo $user->getUsername(); ?></a></td>
            <td><?php echo $user->getName(); ?></td>
            <td><?php echo (int)$user->$solvedMethod(); ?></td>
            <td><?php echo round((float)$user->$scoreMethod(), 3); ?></td>
        </tr>
    <?php endforeach ?>
</table>