<div class="row">
    <div class="col-md-12">
        <h2><?php echo $title; ?></h2>
        <hr/>
    </div>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Score</th>
        <th>Problems solved</th>
    </tr>
    </thead>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><a href='#'><?php echo $user->getUsername(); ?></a></td>
            <td><?php echo $user->getName(); ?></td>
            <td><?php echo (int)$user->$scoreMethod(); ?></td>
            <td><?php echo (int)$user->$solvedMethod(); ?></td>

        </tr>
    <?php endforeach ?>
</table>