<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class JudgeDocumentMiscUserSubmissionHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="date") */
        if (isset($data['tc'])) {
            $value = $data['tc'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } elseif ($value instanceof \DateTime) { $return = $value; } else { $return = new \DateTime($value); }
            $this->class->reflFields['timeCreated']->setValue($document, clone $return);
            $hydratedData['timeCreated'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['solved'])) {
            $value = $data['solved'];
            $return = (bool) $value;
            $this->class->reflFields['solved']->setValue($document, $return);
            $hydratedData['solved'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['answer'])) {
            $value = $data['answer'];
            $return = (string) $value;
            $this->class->reflFields['answer']->setValue($document, $return);
            $hydratedData['answer'] = $return;
        }

        /** @Field(type="object_id") */
        if (isset($data['pid'])) {
            $value = $data['pid'];
            $return = (string) $value;
            $this->class->reflFields['problemId']->setValue($document, $return);
            $hydratedData['problemId'] = $return;
        }

        /** @Field(type="object_id") */
        if (isset($data['uid'])) {
            $value = $data['uid'];
            $return = (string) $value;
            $this->class->reflFields['userId']->setValue($document, $return);
            $hydratedData['userId'] = $return;
        }

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }
        return $hydratedData;
    }
}