<h2>Tutorials</h2>
<hr />
<table class="table table-striped table-advance table-hover">
    <thead>
    <tr>
        <th>Title</th>
    </tr>
    </thead>
    <?php foreach ($tutorials as $tutorial): ?>
        <tr>
            <td><a href="<?php echo $this->url('tutorial-view/default', array('action'=>'view', 'id' => (string)$tutorial->getId())); ?>"><?php echo $tutorial->getTitle(); ?></a></td>
        </tr>
    <?php endforeach ?>
</table>